### PR TITLE
we fixed some incorrect object types

### LINKED ISSUE #189: js-controller 3.3.x
image

### PR DESCRIPTION
**Pull request by foxriver76**
closes #189

### CODE REVIEW

**Comment by foxriver76** [comment]
I've also added a fix for the sentry logging which is really confusing when the user (like me) has disabled sentry + fixed the grammar of the message. Also added a changelog entry so all what is left to do is merge + run release script ;-)

**Comment by DutchmanNL** [comment]
Great will Look Into Next days busy with holiday 🙈😉

**Comment by foxriver76** [comment]
> busy with holiday

Enjoy 😊 

doing the same right now

**Comment by DutchmanNL** [comment]
will fix testing in new commit

**Pull request merged**
